<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AI_Data_Analyzer</RootNamespace>
    <UserSecretsId>5e6b281c-53a4-44e1-86e5-10ccc970a0aa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Uploads\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

</Project>
